/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
Participantes:
Juan Pablo Rufino Mesquita
Felipe Kauan dos Santos Silva
Alisson Rodrigues
*/

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"


#define GPIO_PIN_4                 ((uint16_t)0x0010)  /* Pin 4 selected    */
#define GPIO_PIN_5                 ((uint16_t)0x0020)  /* Pin 5 selected    */
#define GPIO_PIN_6                 ((uint16_t)0x0040)  /* Pin 6 selected    */
#define GPIO_PIN_7                 ((uint16_t)0x0080)  /* Pin 7 selected    */

#define GPIO_PIN_10                ((uint16_t)0x0400)  /* Pin 10 selected   */
#define GPIO_PIN_11                ((uint16_t)0x0800)  /* Pin 11 selected   */

#define GPIO_PIN_13                ((uint16_t)0x2000)  /* Pin 13 selected   */

int main(void)
{

	RCC->CR |= RCC_CR_HSEON;
	// Set Bit 3 to enable GPIOB clock
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN;

	// Make GPIOB Pin5,6,7 output
    // Configuração de PA5, PA6, PA7 como saída push-pull
    GPIOA->CRL &= ~(GPIO_CRL_MODE5 | GPIO_CRL_CNF5 | GPIO_CRL_MODE6 | GPIO_CRL_CNF6 | GPIO_CRL_MODE7 | GPIO_CRL_CNF7);
    GPIOA->CRL |= (GPIO_CRL_MODE5_1 | GPIO_CRL_MODE6_1 | GPIO_CRL_MODE7_1);  // Output de até 2 MHz

	// Make GPIOC Pin10,11 input
    GPIOA->CRH &= ~(GPIO_CRH_MODE10 | GPIO_CRH_CNF10 | GPIO_CRH_MODE11 | GPIO_CRH_CNF11);
    GPIOA->CRH |= (GPIO_CRH_CNF10_1 | GPIO_CRH_CNF11_1);

	// Make GPIOB Pin4 input
    GPIOB->CRL &= ~(GPIO_CRL_MODE4 | GPIO_CRL_CNF4);
    GPIOB->CRL |= GPIO_CRL_CNF4_1;

	// Make GPIOC Pin13 output
	GPIOC->CRH &= ~(GPIO_CRH_MODE13 | GPIO_CRH_CNF13);
	GPIOC->CRH |= GPIO_CRH_MODE13_1;

	// Reset GPIOC Pin13
	GPIOC->ODR &= ~(1 << 13);

	// Reset GPIOA Pin5,6,7
	GPIOB->ODR &= ~((1 << 5)|(1 << 6)|(1 << 7));

	GPIOC->ODR |= GPIO_PIN_13;


	while(1){

		if((GPIOB->IDR & GPIO_PIN_4) != 0){
			GPIOA->ODR |= GPIO_PIN_7;
		}
		else{
			GPIOA->ODR &= ~GPIO_PIN_7;
		}

		if ((GPIOA->IDR & GPIO_PIN_10) != 0) {
			GPIOA->ODR |= GPIO_PIN_5;
		} else {
			GPIOA->ODR &= ~GPIO_PIN_5;
		        }

		if ((GPIOA->IDR & GPIO_PIN_11) != 0) {
			GPIOA->ODR |= GPIO_PIN_6;
		} else {
			GPIOA->ODR &= ~GPIO_PIN_6;
		}

	}
}
